apiVersion: v1
kind: Secret
metadata:
  name: roundcube-secret
  namespace: mail-system
type: Opaque
# for demo purposes only
stringData:
  ROUNDCUBEMAIL_DB_PASSWORD: "CorpDbMailPass2026!"
  ROUNDCUBEMAIL_DES_KEY: "rcmail-secure-corp-key-2026-x9z!"
