Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_check_update = false

  nodes = [
    { name: "master",  ip: "192.168.56.10", ram: "1024", cpu: 1 },
    { name: "worker1", ip: "192.168.56.11", ram: "1024", cpu: 1 },
    { name: "worker2", ip: "192.168.56.12", ram: "1024", cpu: 1 }
  ]

  nodes.each do |n|
    config.vm.define n[:name] do |node|
      node.vm.hostname = n[:name]
      node.vm.network "private_network", ip: n[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.name = n[:name]
        vb.memory = n[:ram]
        vb.cpus = n[:cpu]
        vb.linked_clone = true
      end
    end
  end
end
