apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mail-system
type: Opaque
# for demo purposes only
stringData:
  MYSQL_ROOT_PASSWORD: "CorpDbRootPass2026!"
  MYSQL_DATABASE: "roundcubemail"
  MYSQL_USER: "roundcube"
  MYSQL_PASSWORD: "CorpDbMailPass2026!"
