apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret
  namespace: mail-system
type: Opaque

# passwords shouldn't be visible in a production environments.
# this is for demo purposes only.
stringData:
  LDAP_ADMIN_PASSWORD: "O(vmS%j+4$[&ZSr!"
  LDAP_CONFIG_PASSWORD: "8c.e_P>{ty2?!^T+"
