[masters]
master ansible_host=192.168.56.10

[workers]
worker1 ansible_host=192.168.56.11
worker2 ansible_host=192.168.56.12

[edge_nodes]
master
worker1

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=../vagrant/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key
ansible_python_interpreter=/usr/bin/python3
