---
- name: Hardening for All Servers
  hosts: all
  become: True
  roles:
    - hardening

- name: Edge Ingress and WAF Layer
  hosts: edge_nodes
  become: true
  tags: ingress
  roles:
    - keepalived
    - nginx
    - waf

- name: K3s
  hosts: masters, workers
  become: true
  roles:
    - k3s

- name: Deploy GitOps Controller (ArgoCD)
  hosts: masters
  become: true
  roles:
    - argocd
