apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ali-safapour/my-cloud-platform.git'
    targetRevision: main
    path: k8s/workloads/mariadb
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mail-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
